OnGetDemo/Models/ParamsModel.cs
namespace OnGetDemo.Models;

public class ParamsModel
{
    public int Param1 { get; set; } = -1;
    public int Param2 { get; set; } = -1;
}

OnGetDemo/Pages/Error.cshtml.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OnGetDemo.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }

}

OnGetDemo/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OnGetDemo.Models;
using System.ComponentModel.DataAnnotations;

namespace OnGetDemo.Pages
{
    public class IndexModel : PageModel
    {
        [BindProperty(SupportsGet = true)]
        public int Param1 { get; set; }

        [BindProperty(SupportsGet = true)]
        public int Param2 { get; set; }

        [BindProperty]
        public ParamsModel Params { get; set; } = new();

        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }

        public void OnPost()
        {
            _logger.LogError($"OnPost Param1: {Param1}");
        }

        // you have to make the return type IActionResult if you want to do a redirect
        public IActionResult OnPostHandler1()
        {
            _logger.LogError($"OnPostHander1 Param1: {Param1}");
            // return the redirect
            return RedirectToPage("Privacy");
            // if you want to pass variables you do so by making a new
            // anonymous object with the variable names in it
            // we could just say Param1 here instead of Param1 = Param1
            // since the names are the same
            // comma separate multiple values
            //return RedirectToPage("Privacy", new { Param1 = Param1 });
        }

        public void OnPostHandler2()
        {
            _logger.LogError($"OnPostHander2 Param1: {Param1}");
        }

        // the OnPost handler for our form that uses a Model
        public IActionResult OnPostParamsModel()
        {
            _logger.LogError($"OnPostParamsModel Param1: {Params.Param1}");

            // this just reloads the index page again, but it will have a PersonModel
            // with a value for Param1
            //return Page();

            //return RedirectToPage("Privacy", new { Param1=Params.Param1, Param2=34});//Params);

            // redirect using a POST
            // we can pass our Params object to the next page since its properties
            // line up with the properties the Privacy page is looking for
            // Param1, Param2
            return RedirectToPagePreserveMethod("Privacy", null, Params);
        }
    }
}

OnGetDemo/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace OnGetDemo.Pages
{
    [BindProperties(SupportsGet = true)]
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        [BindProperty(SupportsGet = true)]
        public int Param1 { get; set; } = 0;

        [BindProperty(SupportsGet = true)]
        public int Param2 { get; set; } = 0;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            _logger.LogError($"Privacy - OnGet - {Param1} - {Param2}");
        }

        public void OnPost()
        {
            _logger.LogError($"Privacy - OnPost - {Param1} - {Param2}");
        }
    }

}

OnGetDemo/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";

    // let me be clear this is not the right way to do this
    // this is just for demo purposes
    // we really want to put most of our variables in our view model (code behind)
    // and we will moving forward
    int param1 = 5;
}

<!-- these work but aren't the best of way of doing a link in Razor Pages -->
<ul class="m-5">
    <li><a href="~/Privacy?param1=2&param2=3">Privacy param1=2 param2=3</a></li>
    <li><a href="~/Privacy?param1=20&param2=30">Privacy param1=20 param2=30</a></li>
</ul>

<!-- what if we wanted to pass a variable as a parameter? -->
<!-- you can make it work doing something like this -->
<!-- but Razor Pages gives us a little nicer way of doing it -->
<ul class="m-5">
    <li><a href="~/Privacy?param1=@param1&param2=3">Privacy param1=@param1 param2=3</a></li>
</ul>

<!-- instead we want to use some built in tag helpers -->
<!-- https://learn.microsoft.com/en-us/aspnet/core/mvc/views/tag-helpers/built-in/anchor-tag-helper?view=aspnetcore-9.0 -->
<ul class="m-5">
    <li><a asp-page="Privacy" asp-route-param1="9" asp-route-param2="10">The right way #1</a></li>
    <li><a asp-page="Privacy" asp-route-param1="@param1" asp-route-param2="10">The right way with variable</a></li>
</ul>

<!-- we can also do a get using a form -->
<form method="get" asp-page="Privacy" class="m-5">
    <h5>GET</h5>
    <!-- this requires we have a Param1 property for this view's view-model
    even though we are sending the GET to the privacy page 
    the names of the two variables need to match 
    -->
    <label asp-for="Param1"></label>
    <input type="text" asp-for="Param1" />   
    <input type="submit" />
</form>

<!-- cross post 
NOTE: we can have multiple forms on the same page
-->
<form method="post" asp-page="Privacy" class="m-5">
    <h5>CROSS POST</h5>
    <label asp-for="Param1"></label>
    <input type="text" asp-for="Param1" />
    <label asp-for="Param2"></label>
    <input type="text" asp-for="Param2" />
    <input type="submit" />
</form>

<!-- postback -->
<form method="post" class="m-5">
    <h5>POSTBACK</h5>
    <label asp-for="Param1"></label>
    <input type="text" asp-for="Param1" />
    <input type="submit" />
</form>

<!-- postback to handler1 -->
<form method="post" class="m-5">
    <h5>handler1 POSTBACK</h5>
    <label asp-for="Param1"></label>
    <input type="text" asp-for="Param1" />
    <input type="submit" asp-page-handler="handler1" />
</form>

<!-- postback to handler2 
NOTE: you can also use button instead of intput with type submit
the default appearance is different
and you can move the asp-page helper tag from the form to the button
which allows multiple buttons in the same form that submit different ways
-->
<form method="post" class="m-5">
    <h5>handler2 POSTS</h5>
    <label asp-for="Param1"></label>
    <input type="text" asp-for="Param1" />
    <button type="submit" asp-page="Index" asp-page-handler="handler2">Postback</button>
    <button type="submit" asp-page="Privacy" asp-page-handler="handler2">Privacy</button>
</form>

<!-- here we are going to do a POST and use a Model to contain our data -->
<form method="post" class="m-5">
    <!-- if PersonModel is null it will crash if you reference it -->
    <!-- if we just reload this page instead of doing a redirect the PersonModel will not be null -->
    @if (Model.Params != null)
    {
        <h5>POSTBACK using a MODEL (Param1 value: @Model.Params.Param1)</h5>
    }
    else
    {
        <h5>POSTBACK using a MODEL</h5>
    }
    <label asp-for="Params.Param1"></label>
    <input type="text" asp-for="Params.Param1" />
    <button type="submit" asp-page="Index" asp-page-handler="ParamsModel">Submit</button>
</form>

<!-- wanted to add a demo of a for loop formatting a string for your assignment -->
<div class="m-5">
@for(int i = 0; i < 3; i++)
{
    string msg = $"i = {i}";
    <div>@msg</div>
}
</div>

<!-- deom of using an Html helper function -->
<h1 class="m-5">@Html.DisplayNameFor(m => m.Params.Param1)</h1>

OnGetDemo/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnGetDemo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/OnGetDemo.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">OnGetDemo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - OnGetDemo - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>